EXAMPLES = {

    "sys_microservices": {
        "title": "E-Commerce Platform — Service Architecture",
        "description": "Microservices architecture for a mid-size e-commerce platform. Each service owns its database. The API Gateway is the only public-facing entry point.",
        "nodes": [
            {"id": "client",    "label": "Web Client",        "kind": "external", "description": "React SPA served via CDN"},
            {"id": "mobile",    "label": "Mobile App",        "kind": "external", "description": "iOS/Android, talks directly to gateway"},
            {"id": "gateway",   "label": "API Gateway",       "kind": "service",  "description": "Auth, rate-limiting, routing. Only public-facing entry point.", "tech": "nginx + lua", "tags": ["critical", "public-facing"]},
            {"id": "orders",    "label": "Order Service",     "kind": "service",  "description": "Create, fulfill, cancel orders. Emits OrderPlaced events.", "tech": "Go", "owner": "fulfillment-team"},
            {"id": "inventory", "label": "Inventory Service", "kind": "service",  "description": "Tracks stock levels. Subscribes to OrderPlaced to reserve stock.", "tech": "Go", "owner": "fulfillment-team"},
            {"id": "payments",  "label": "Payment Service",   "kind": "service",  "description": "Charge and refund. Talks to Stripe.", "tech": "Node.js", "owner": "payments-team", "tags": ["pci-scope"]},
            {"id": "users",     "label": "User Service",      "kind": "service",  "description": "Profile, auth tokens, preferences.", "tech": "Python", "owner": "platform-team"},
            {"id": "notify",    "label": "Notification Svc",  "kind": "service",  "description": "Email and push. Consumes events from the bus.", "tech": "Python", "owner": "platform-team"},
            {"id": "orderdb",   "label": "Orders DB",         "kind": "db",       "tech": "PostgreSQL"},
            {"id": "invdb",     "label": "Inventory DB",      "kind": "db",       "tech": "PostgreSQL"},
            {"id": "paydb",     "label": "Payments DB",       "kind": "db",       "tech": "PostgreSQL"},
            {"id": "userdb",    "label": "Users DB",          "kind": "db",       "tech": "PostgreSQL"},
            {"id": "bus",       "label": "Event Bus",         "kind": "queue",    "description": "Async domain events (OrderPlaced, PaymentFailed, etc.)", "tech": "Kafka"},
            {"id": "stripe",    "label": "Stripe",            "kind": "external", "description": "Payment processor"},
        ],
        "edges": [
            {"from": "client",    "to": "gateway",   "kind": "calls",      "label": "HTTPS"},
            {"from": "mobile",    "to": "gateway",   "kind": "calls",      "label": "HTTPS"},
            {"from": "gateway",   "to": "orders",    "kind": "calls",      "label": "REST"},
            {"from": "gateway",   "to": "users",     "kind": "calls",      "label": "REST"},
            {"from": "gateway",   "to": "inventory", "kind": "calls",      "label": "REST"},
            {"from": "orders",    "to": "payments",  "kind": "calls",      "label": "gRPC"},
            {"from": "orders",    "to": "orderdb",   "kind": "writes",     "label": "SQL"},
            {"from": "orders",    "to": "bus",       "kind": "emits",      "label": "OrderPlaced"},
            {"from": "inventory", "to": "invdb",     "kind": "writes",     "label": "SQL"},
            {"from": "inventory", "to": "bus",       "kind": "subscribes", "async": True},
            {"from": "payments",  "to": "paydb",     "kind": "writes",     "label": "SQL"},
            {"from": "payments",  "to": "stripe",    "kind": "calls",      "label": "HTTPS"},
            {"from": "users",     "to": "userdb",    "kind": "writes",     "label": "SQL"},
            {"from": "notify",    "to": "bus",       "kind": "subscribes", "async": True},
        ],
        "groups": [
            {"id": "public",      "label": "Public Zone",    "kind": "layer",  "members": ["client", "mobile"]},
            {"id": "edge",        "label": "Edge Layer",     "kind": "layer",  "members": ["gateway"]},
            {"id": "fulfillment", "label": "Fulfillment",    "kind": "domain", "members": ["orders", "inventory", "orderdb", "invdb"]},
            {"id": "data",        "label": "Data Layer",     "kind": "layer",  "members": ["orderdb", "invdb", "paydb", "userdb"]},
        ]
    },

    "sys_event_driven": {
        "title": "Data Ingestion Pipeline",
        "description": "Event-driven pipeline for ingesting, transforming, and storing telemetry data from IoT devices.",
        "nodes": [
            {"id": "device",    "label": "IoT Device",       "kind": "external", "description": "Publishes telemetry at up to 1 Hz"},
            {"id": "ingest",    "label": "Ingest API",        "kind": "service",  "description": "Validates and fans out inbound events", "tech": "Go", "tags": ["high-throughput"]},
            {"id": "raw",       "label": "Raw Events Topic",  "kind": "queue",    "tech": "Kafka", "description": "Unprocessed events, 7-day retention"},
            {"id": "transform", "label": "Transform Worker",  "kind": "service",  "description": "Normalizes units, deduplicates, enriches with device metadata", "tech": "Python"},
            {"id": "dlq",       "label": "Dead Letter Queue", "kind": "queue",    "tech": "Kafka", "description": "Failed transform events for investigation"},
            {"id": "enriched",  "label": "Enriched Topic",    "kind": "queue",    "tech": "Kafka", "description": "Processed, ready-to-store events"},
            {"id": "loader",    "label": "Batch Loader",      "kind": "service",  "description": "Micro-batches enriched events into the warehouse", "tech": "Python"},
            {"id": "warehouse", "label": "Data Warehouse",    "kind": "db",       "tech": "BigQuery", "description": "Long-term storage, queried by analysts"},
            {"id": "stream",    "label": "Stream Processor",  "kind": "service",  "description": "Windowed aggregations for real-time dashboards", "tech": "Flink"},
            {"id": "cache",     "label": "Metrics Cache",     "kind": "db",       "tech": "Redis",    "description": "Latest aggregates, TTL 60s"},
            {"id": "api",       "label": "Dashboard API",     "kind": "service",  "description": "Serves real-time and historical metrics to the UI", "tech": "Go"},
            {"id": "ui",        "label": "Dashboard UI",      "kind": "external", "description": "Analyst-facing dashboard"},
        ],
        "edges": [
            {"from": "device",    "to": "ingest",    "kind": "calls",      "label": "HTTPS POST"},
            {"from": "ingest",    "to": "raw",       "kind": "emits",      "label": "publish"},
            {"from": "transform", "to": "raw",       "kind": "subscribes", "async": True},
            {"from": "transform", "to": "enriched",  "kind": "emits",      "label": "publish"},
            {"from": "transform", "to": "dlq",       "kind": "emits",      "label": "on error", "async": True},
            {"from": "loader",    "to": "enriched",  "kind": "subscribes", "async": True},
            {"from": "loader",    "to": "warehouse", "kind": "writes",     "label": "batch insert"},
            {"from": "stream",    "to": "enriched",  "kind": "subscribes", "async": True},
            {"from": "stream",    "to": "cache",     "kind": "writes",     "label": "aggregates"},
            {"from": "api",       "to": "cache",     "kind": "reads",      "label": "real-time"},
            {"from": "api",       "to": "warehouse", "kind": "reads",      "label": "historical"},
            {"from": "ui",        "to": "api",       "kind": "calls",      "label": "HTTPS"},
        ],
        "groups": [
            {"id": "ingestion",  "label": "Ingestion",   "kind": "layer", "members": ["ingest", "raw"]},
            {"id": "processing", "label": "Processing",  "kind": "layer", "members": ["transform", "dlq", "enriched"]},
            {"id": "storage",    "label": "Storage",     "kind": "layer", "members": ["loader", "warehouse", "stream", "cache"]},
            {"id": "serving",    "label": "Serving",     "kind": "layer", "members": ["api", "ui"]},
        ]
    },

    "sys_monolith": {
        "title": "Rails Monolith — Module Architecture",
        "description": "Module-level view of a Rails monolith before a planned decomposition. Dashed edges highlight the coupling that makes decomposition hard.",
        "nodes": [
            {"id": "web",      "label": "Web Controllers",   "kind": "module",   "description": "ActionController subclasses, session handling, routing", "tech": "Rails"},
            {"id": "api",      "label": "API Controllers",   "kind": "module",   "description": "JSON API endpoints, token auth", "tech": "Rails"},
            {"id": "billing",  "label": "Billing",           "kind": "module",   "description": "Subscription management, invoicing, Stripe sync", "tech": "Ruby", "owner": "payments-team", "tags": ["decompose-candidate"]},
            {"id": "auth",     "label": "Auth",              "kind": "module",   "description": "Devise + custom RBAC, JWT issuance", "tech": "Ruby", "owner": "platform-team"},
            {"id": "notifs",   "label": "Notifications",     "kind": "module",   "description": "Email, in-app, push. Uses ActionMailer + Noticed gem", "tech": "Ruby", "tags": ["decompose-candidate"]},
            {"id": "jobs",     "label": "Background Jobs",   "kind": "module",   "description": "Sidekiq workers — renewal, digest emails, exports", "tech": "Sidekiq"},
            {"id": "reports",  "label": "Reports",           "kind": "module",   "description": "SQL-heavy reporting, CSV export", "tech": "Ruby", "tags": ["slow"]},
            {"id": "models",   "label": "ActiveRecord Models","kind": "module",  "description": "Shared data layer — User, Account, Subscription, Invoice, etc.", "tech": "Rails"},
            {"id": "db",       "label": "PostgreSQL",        "kind": "db",       "tech": "PostgreSQL 15"},
            {"id": "redis",    "label": "Redis",             "kind": "db",       "tech": "Redis 7", "description": "Sidekiq queue + session store"},
            {"id": "stripe",   "label": "Stripe",            "kind": "external"},
            {"id": "ses",      "label": "AWS SES",           "kind": "external", "description": "Email delivery"},
        ],
        "edges": [
            {"from": "web",     "to": "auth",     "kind": "depends",  "label": "before_action"},
            {"from": "web",     "to": "models",   "kind": "reads",    "label": "ActiveRecord"},
            {"from": "api",     "to": "auth",     "kind": "depends",  "label": "JWT verify"},
            {"from": "api",     "to": "models",   "kind": "reads"},
            {"from": "billing", "to": "models",   "kind": "writes",   "label": "Subscription/Invoice"},
            {"from": "billing", "to": "stripe",   "kind": "calls",    "label": "HTTPS"},
            {"from": "billing", "to": "notifs",   "kind": "calls",    "label": "payment events", "async": True},
            {"from": "auth",    "to": "models",   "kind": "reads",    "label": "User/Account"},
            {"from": "notifs",  "to": "ses",      "kind": "calls",    "label": "SMTP"},
            {"from": "notifs",  "to": "models",   "kind": "reads"},
            {"from": "jobs",    "to": "billing",  "kind": "calls",    "label": "renewal job"},
            {"from": "jobs",    "to": "notifs",   "kind": "calls",    "label": "digest job"},
            {"from": "jobs",    "to": "redis",    "kind": "reads",    "label": "queue"},
            {"from": "reports", "to": "models",   "kind": "reads",    "label": "direct SQL"},
            {"from": "models",  "to": "db",       "kind": "reads"},
        ],
        "groups": [
            {"id": "frontend",  "label": "Presentation",  "kind": "layer", "members": ["web", "api"]},
            {"id": "domain",    "label": "Domain",        "kind": "layer", "members": ["billing", "auth", "notifs", "reports"]},
            {"id": "infra",     "label": "Infrastructure","kind": "layer", "members": ["jobs", "models", "db", "redis"]},
        ]
    },
}
